-- [Reset] 기존 테이블 삭제 (순서 중요: 의존성 역순)
drop table if exists scheduled_messages;
drop table if exists message_templates;
drop table if exists reservations;
drop table if exists rooms;
drop table if exists businesses;

-- [1] 업체 계정 테이블 (사용자별 1개)
create table businesses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null, -- Supabase Auth User
  name text not null,
  owner_name text not null,
  contact_phone text not null, -- 발송 실패 알림 수신용
  email text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique (user_id)
);

-- [2] 숙소 목록 테이블
create table rooms (
  id bigint generated by default as identity primary key,
  business_id bigint references businesses(id) on delete cascade not null,
  name text not null,
  color text, -- 관리자 지정 숙소별 고유 캘린더/뱃지 테마 색상 (hex)
  lock_password text, -- 숙소별 잠금 비밀번호 (null이면 잠금 없음)
  options text[] default '{}', -- 숙소별 부가 옵션 (최대 10개)
  staff_members jsonb default '[]', -- 숙소별 직원(이모님) 목록 [{name, phone}, ...]
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- [3] 예약 정보 테이블
create table reservations (
  id bigint generated by default as identity primary key,
  business_id bigint references businesses(id) on delete cascade not null,
  room_id bigint references rooms(id) on delete cascade not null,
  guest_name text not null,
  phone text not null,
  check_in date not null,
  check_out date not null,
  memo text,
  selected_options text[] default '{}', -- 예약시 선택한 부가 옵션 리스트
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- [4] 메시지 템플릿 테이블 (숙소별)
create table message_templates (
  id bigint generated by default as identity primary key,
  room_id bigint references rooms(id) on delete cascade not null,
  title text not null,
  content text not null,
  image_url text, -- MMS용 Supabase Storage URL
  trigger_type text not null check (trigger_type in ('checkin', 'checkout', 'staying')),
  recipient_type text default 'guest' check (recipient_type in ('guest', 'staff')),
  send_time time not null, -- (예: '09:00:00')
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Upsert 처리를 위한 유니크 제약조건 (방/트리거/대상/시간 조합이 고유하게)
  unique (room_id, trigger_type, recipient_type, send_time)
);

-- [5] 문자 발송 스케줄 테이블 (예약 등록시 자동 생성 + 크론 폴링 대상)
create table scheduled_messages (
  id bigint generated by default as identity primary key,
  reservation_id bigint references reservations(id) on delete cascade not null,
  template_id bigint references message_templates(id) on delete cascade,
  scheduled_at timestamp with time zone not null, -- 실제 발송되어야 할 시간
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed')),
  sent_at timestamp with time zone,
  error_message text,
  
  -- "예약ID + 템플릿ID" 중복 생성 방지용 (동일 메시지 2번 전송 방지)
  unique (reservation_id, template_id)
);

-- RLS (Row Level Security) 설정 (관리자 권한은 auth.users 의 metadata나 별도 판단)
alter table businesses enable row level security;
alter table rooms enable row level security;
alter table reservations enable row level security;
alter table message_templates enable row level security;
alter table scheduled_messages enable row level security;

-- 일반 사업자(business) 정책 예시
CREATE POLICY "Businesses can view their own data." ON businesses FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Businesses can update their own data." ON businesses FOR UPDATE USING (auth.uid() = user_id);
-- ... 등등 프로젝트에 맞게 자유롭게 설정 (추후 보완)
